# Use postgres/example user/password credentials
version: '3.1'

services:

  financedb:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: myfinancesdb
      POSTGRES_PASSWORD: postgres
    #  - PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
